### ISSUE TITLE
Bug: TTS reading full stops as "dot"

### ISSUE THREAD

**Issue by HaggardHare** [ken107/piper-browser-extension#8]
Tried a few voice models, all have the same issue. The voice quality is great outside of this, but the bug makes it unusable.

**Comment by ken107** [comment]
Please provide the URL of the page, and the name of the voice you're using when you encounter this issue.

You can tell that most users do not encounter this issue, because it would make the extension virtually useless if this happens all the time.  So it is likely the page you're using it on, and the particular voice.

**Comment by 121tech** [comment]
The Piper voice models voicing the '.' as "dot" just started occurring today. I initially thought it was just an issue with my normal Read Aloud chrome browser extension, but after using other Piper TTS products, they all appear to be voicing the '.' as "dot" now, so I assume this is something changed overnight with the Piper voice model files.

As to ken107's request, having any of my Windows loaded Piper programs voice the bug page results in the '.' being voiced as "dot" being replicated.

**Comment by ken107** [comment]
Thank you for clarifying.  I will take a look then.  Much appreciated.

**Comment by 121tech** [comment]
This issue appears to have been resolved, as the Piper voice had stopped voicing the end of sentence '.' as "dot"

I was guessing someone or something had edited a phonemes file on the cloud server side, and this edit has been reversed or the logic has been updates.  Thanks for willing to look at it.

**Comment by ken107** [comment]
Ah, yes, turns out to be the piper-phonemize program being fairly buggy and became corrupted somehow. I restarted the docker image and it works correctly again.  That program is a black box because of its reliance on legacy espeak libraries, the developer of Piper is planning to move away from espeak.  Hopefully we won't have to deal with this too often.
